export const CALENDAR_VISIBLE_WEEKS = 5;
export const CALENDAR_BUFFER_WEEKS = 5;
export const CALENDAR_WINDOW_WEEKS = CALENDAR_VISIBLE_WEEKS + (CALENDAR_BUFFER_WEEKS * 2);
export const CALENDAR_WEEK_ROW_HEIGHT = 320;
export const CALENDAR_PREVIEW_VISIBLE_HEIGHT = Math.round(CALENDAR_WEEK_ROW_HEIGHT * 0.3);
export const CALENDAR_ANCHOR_SCROLL_TOP = CALENDAR_WEEK_ROW_HEIGHT - CALENDAR_PREVIEW_VISIBLE_HEIGHT;
export const CALENDAR_SHIFT_WEEKS = 1;
